apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpipe
  labels:
    app: testpipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpipe
  template:
    metadata:
      labels:
        app: testpipe
    spec:
      containers:
      - name: testpipe
        image: testpipe:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: testpipe
  labels:
    app: testpipe
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: testpipe
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testpipe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /sum
        backend:
          serviceName: testpipe
          servicePort: 8080