pipeline:
    stages:
        build:
            - maven:
                package:
                    path: .
        release:
            - exec:
                path: build.sh
        deploy:
            - kube:
                path: pipelines/deploy.yaml